import { ApiProperty } from '@nestjs/swagger';
import { IsEnum, IsNotEmpty, IsObject, IsOptional, IsString } from 'class-validator';
import { segmentType } from '../enums/segementType.enum';

export class CreateSegmentDto {

  @ApiProperty({
    example: 'High Value Customers',
    description: 'Name of the segment',
  })
  @IsString()
  @IsNotEmpty()
  name: string;

  @ApiProperty({
    example: 'Customers who placed more than 3 orders',
    description: 'Segment description',
    required: false,
  })
  @IsOptional()
  @IsString()
  description?: string;

  @ApiProperty({
    enum: segmentType,
    example: segmentType.USER_SEGMENT,
    description: 'Type of segment',
  })
  @IsEnum(segmentType)
  segmentType: segmentType;

  @ApiProperty({
    description: 'Criteria JSON generated by segment builder UI',
    example: {
        event: 'BIRTHDAY',
        comparison: 'IS',
        operator: 'BETWEEN',
        startDate: new Date(),
        endDate: new Date(),
    },
  })
  
  criteria: Record<string, any>;
}
