import { ApiProperty } from '@nestjs/swagger';
import {
  IsArray,
  IsEnum,
  IsNotEmpty,
  IsObject,
  IsOptional,
  IsString,
  ValidateNested,
} from 'class-validator';
import { Type } from 'class-transformer';
import { segmentType } from '../enums/segementType.enum';

export class SegmentCriteriaItemDto {
  @ApiProperty({
    description: 'Type of criteria (e.g. MEMBERS_CRITERIA, STOCK_LEVEL)',
    example: 'MEMBERS_CRITERIA',
  })
  @IsString()
  @IsNotEmpty()
  criteriaType: string;

  @ApiProperty({
    description: 'Criteria JSON generated by segment builder UI',
    example: {
      rules: 'BIRTHDAY',
      conditions: 'IS',
      comparisionOpreator: 'BETWEEN',
      startDate: new Date(),
      endDate: new Date(),
    },
  })
  @IsObject()
  @IsNotEmpty()
  criteria: Record<string, any>;
}

export class CreateSegmentDto {
  @ApiProperty({
    example: 'High Value Customers',
    description: 'Name of the segment',
  })
  @IsString()
  @IsNotEmpty()
  name: string;

  @ApiProperty({
    example: 'Customers who placed more than 3 orders',
    description: 'Segment description',
    required: false,
  })
  @IsOptional()
  @IsString()
  description?: string;

  @ApiProperty({
    enum: segmentType,
    example: segmentType.USER_SEGMENT,
    description: 'Type of segment',
  })
  @IsEnum(segmentType)
  segmentType: segmentType;

  @ApiProperty({
    type: [SegmentCriteriaItemDto],
    description: 'List of criteria for the segment',
  })
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => SegmentCriteriaItemDto)
  @IsNotEmpty()
  selectedCriterias: SegmentCriteriaItemDto[];
}
