export enum EngagementRuleType {
    SPECIFIC_CAMPAIGN = 'SPECIFIC_CAMPAIGN',
    ANY_COMMUNICATION = 'ANY_COMMUNICATION',
    ANY_EMAIL = 'ANY_EMAIL',
    ANY_SMS = 'ANY_SMS',
    ANY_WHATSAPP = 'ANY_WHATSAPP',
    ANY_PUSH_NOTIFICATION = 'ANY_PUSH_NOTIFICATION',

}