export enum ProductInteractionRule {
  ADDED_TO_CART_BUT_NOT_PURCHASED = 'ADDED_TO_CART_BUT_NOT_PURCHASED',
  REACHED_CHECKOUT_BUT_ABANDONED = 'REACHED_CHECKOUT_BUT_ABANDONED',
  PRODUCT_VIEWED_BUT_NOT_PURCHASED = 'PRODUCT_VIEWED_BUT_NOT_PURCHASED',
}
