export enum TransactionRules {
  TOTAL_AMOUNT_SPEND = 'TOTAL_AMOUNT_SPEND',
  RECENT_PURCHASE_DATE = 'RECENT_PURCHASE_DATE',
  PURCHASE_FREQUENCY = 'PURCHASE_FREQUENCY',
  AVERAGE_ORDER_VALUE = 'AVERAGE_ORDER_VALUE',
}
