export enum UserCriteria {
    MEMBERS_CRITERIA = 'MEMBERS_CRITERIA',
    ENGAGEMENT_CRITERIA = 'ENGAGEMENT_CRITERIA',
    DISCOUNT_CRITERIA = 'DISCOUNT_CRITERIA',
    TRANSACTION_CRITERIA = 'TRANSACTION_CRITERIA',
}
